const canvas = document.querySelector('#game');
const ctx = canvas.getContext('2d');
const $ = s => document.querySelector(s);
let W, H, started = false, last = 0, time = 620, credits = 0, missionStep = 0;
const keys = new Set();
const player = { x: 470, y: 590, a: -1.55, speed: 0, type: 'car' };
const sites = [
  {x:235,y:190,w:205,h:115,name:'图书馆',tag:'知识补给',color:'#d9cda9',action:'在图书馆借到了一本《开放世界设计》',reward:120},
  {x:650,y:180,w:185,h:105,name:'综合教学楼',tag:'上课点',color:'#cbd8d0',action:'上完了一节《数据智能导论》',reward:160},
  {x:205,y:470,w:165,h:115,name:'学一食堂',tag:'干饭点',color:'#dfbb78',action:'吃到了热乎的南开食堂套餐，体力恢复！',reward:80},
  {x:690,y:480,w:165,h:118,name:'体育中心',tag:'运动点',color:'#d9b0aa',action:'在体育中心完成了一圈热身',reward:90},
  {x:445,y:355,w:135,h:85,name:'校史馆',tag:'探索点',color:'#b8c7d8',action:'解锁校园记忆：允公允能，日新月异',reward:150},
];
const runway = {x:120,y:690,w:715,h:72};
const missions = [
  {site:2,title:'第一站：食堂能量',text:'去学一食堂，靠近后按 E 干饭'},
  {site:1,title:'第二站：赶去上课',text:'驾驶前往综合教学楼，按 E 签到'},
  {site:0,title:'第三站：知识补给',text:'去图书馆完成学习任务'},
  {site:4,title:'最终站：校史记忆',text:'去校史馆，完成今日校园漫游'},
];
const pedestrians = Array.from({length:18},(_,i)=>({x:90+(i*83)%800,y:250+(i*47)%430,phase:i*.73,color:['#e86d5d','#405d9c','#f4d261','#6aa88a'][i%4]}));
function resize(){W=canvas.width=innerWidth*devicePixelRatio;H=canvas.height=innerHeight*devicePixelRatio;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)} resize(); addEventListener('resize',resize);
addEventListener('keydown',e=>{ keys.add(e.key.toLowerCase()); if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(e.key))e.preventDefault(); if(e.key.toLowerCase()==='f') switchVehicle(); if(e.key.toLowerCase()==='e') interact(); if(e.key.toLowerCase()==='r') reset();}); addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
$('#start-btn').onclick=()=>{$('#start').style.display='none';started=true;setMission();toast('跑车已就位，第一站：去食堂干饭！')};
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2800)}
function switchVehicle(){player.type=player.type==='car'?'plane':'car';player.speed=0;$('#vehicle').textContent=player.type==='car'?'跑车':'轻型飞机';toast(player.type==='car'?'切换为跑车：地面极速模式':'切换为轻型飞机：按 W 起飞！')}
function reset(){Object.assign(player,{x:470,y:590,a:-1.55,speed:0,type:'car'});$('#vehicle').textContent='跑车';toast('已重置到校园中心')}
function setMission(){const m=missions[missionStep];if(!m){$('#mission-title').textContent='校园漫游完成';$('#mission-text').textContent='你已解锁自由模式：去跑道试飞吧！';return}$('#mission-title').textContent=m.title;$('#mission-text').textContent=m.text}
function interact(){for(let i=0;i<sites.length;i++){const s=sites[i];if(Math.hypot(player.x-s.x-s.w/2,player.y-s.y-s.h/2)<95){if(missionStep<missions.length&&missions[missionStep].site===i){credits+=s.reward;missionStep++;$('#credits').textContent=`校园币 ${credits}`;toast(`${s.action}  +${s.reward} 校园币`);setMission()}else toast(missionStep<missions.length?'这里很棒，不过当前任务还没到这里':'自由探索完成！');return}}toast('靠近带光圈的目标建筑后，按 E 完成任务')}
function update(dt){if(!started)return;const accel=player.type==='car'?145:110, max=player.type==='car'?220:280, turn=player.type==='car'?2.3:1.55; if(keys.has('w')||keys.has('arrowup'))player.speed+=accel*dt;if(keys.has('s')||keys.has('arrowdown'))player.speed-=accel*dt*.75;if(keys.has('a')||keys.has('arrowleft'))player.a-=turn*dt*Math.min(1,Math.abs(player.speed)/45);if(keys.has('d')||keys.has('arrowright'))player.a+=turn*dt*Math.min(1,Math.abs(player.speed)/45);player.speed*=Math.pow(.16,dt);player.speed=Math.max(-max*.32,Math.min(max,player.speed));player.x+=Math.cos(player.a)*player.speed*dt;player.y+=Math.sin(player.a)*player.speed*dt;player.x=Math.max(35,Math.min(925,player.x));player.y=Math.max(35,Math.min(785,player.y));time=(time+dt*3)%1440;pedestrians.forEach((p,i)=>{p.x+=Math.sin(time*.05+p.phase)*dt*7;p.y+=Math.cos(time*.04+p.phase)*dt*4});const h=Math.floor(time/60).toString().padStart(2,'0'),m=Math.floor(time%60).toString().padStart(2,'0');$('#clock').textContent=`${h}:${m}`;$('#speed').textContent=`${Math.round(Math.abs(player.speed)*.73)} km/h`;}
function road(x,y,w,h){ctx.fillStyle='#59656a';ctx.fillRect(x,y,w,h);ctx.fillStyle='#7d898c';ctx.fillRect(x+5,y+5,w-10,h-10);ctx.strokeStyle='#dae1c2';ctx.lineWidth=2;ctx.setLineDash([11,12]);ctx.beginPath();if(w>h){ctx.moveTo(x,y+h/2);ctx.lineTo(x+w,y+h/2)}else{ctx.moveTo(x+w/2,y);ctx.lineTo(x+w/2,y+h)}ctx.stroke();ctx.setLineDash([])}
function building(s,i){if(missionStep<missions.length&&missions[missionStep].site===i){ctx.strokeStyle='#ffe15d';ctx.lineWidth=5;ctx.beginPath();ctx.arc(s.x+s.w/2,s.y+s.h/2,Math.max(s.w,s.h)*.7+Math.sin(time*.15)*5,0,7);ctx.stroke()}ctx.fillStyle='#8c9a91';ctx.fillRect(s.x+8,s.y+9,s.w,s.h);ctx.fillStyle=s.color;ctx.fillRect(s.x,s.y,s.w,s.h);ctx.strokeStyle='#45605a';ctx.lineWidth=3;ctx.strokeRect(s.x,s.y,s.w,s.h);ctx.fillStyle='#233f48';for(let y=s.y+15;y<s.y+s.h-12;y+=19)for(let x=s.x+15;x<s.x+s.w-10;x+=23)ctx.fillRect(x,y,10,8);ctx.fillStyle='#f6ecad';ctx.font='700 14px Noto Sans SC';ctx.textAlign='center';ctx.fillText(s.name,s.x+s.w/2,s.y+s.h/2+5);ctx.font='11px Noto Sans SC';ctx.fillStyle='#33534c';ctx.fillText(s.tag,s.x+s.w/2,s.y+s.h/2+22)}
function pedestrian(p){ctx.fillStyle='#24383255';ctx.beginPath();ctx.ellipse(p.x,p.y+8,5,2,0,0,7);ctx.fill();ctx.fillStyle=p.color;ctx.fillRect(p.x-3,p.y-2,6,10);ctx.fillStyle='#f0bd91';ctx.beginPath();ctx.arc(p.x,p.y-6,4,0,7);ctx.fill()}
function tree(x,y){ctx.fillStyle='#75523a';ctx.fillRect(x-2,y,4,9);ctx.fillStyle='#34755b';ctx.beginPath();ctx.arc(x,y-4,10,0,7);ctx.fill();ctx.fillStyle='#4e9870';ctx.beginPath();ctx.arc(x-3,y-7,6,0,7);ctx.fill()}
function drawVehicle(){ctx.save();ctx.translate(player.x,player.y);ctx.rotate(player.a);if(player.type==='car'){ctx.fillStyle='#142428';ctx.fillRect(-18,-11,36,22);ctx.fillStyle='#f3c82e';ctx.fillRect(-16,-9,32,18);ctx.fillStyle='#88c9da';ctx.fillRect(-7,-7,15,14);ctx.fillStyle='#151b1b';[-12,12].forEach(x=>{ctx.fillRect(x,-13,7,4);ctx.fillRect(x,9,7,4)})}else{ctx.fillStyle='#f0e3b6';ctx.fillRect(-21,-4,42,8);ctx.beginPath();ctx.moveTo(2,-6);ctx.lineTo(-6,-27);ctx.lineTo(13,-6);ctx.fill();ctx.fillStyle='#d34e3e';ctx.fillRect(-10,-21,4,15);ctx.fillStyle='#344f58';ctx.beginPath();ctx.arc(16,0,7,0,7);ctx.fill()}ctx.restore()}
function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);const sc=Math.min(innerWidth/1000,innerHeight/850),ox=(innerWidth-1000*sc)/2,oy=(innerHeight-850*sc)/2;ctx.save();ctx.translate(ox,oy);ctx.scale(sc,sc);ctx.fillStyle='#a5c98d';ctx.fillRect(0,0,1000,850);ctx.fillStyle='#82bfc9';ctx.beginPath();ctx.moveTo(0,80);ctx.bezierCurveTo(120,35,130,110,260,70);ctx.bezierCurveTo(390,25,410,110,555,65);ctx.bezierCurveTo(720,20,820,115,1000,60);ctx.lineTo(1000,0);ctx.lineTo(0,0);ctx.fill();road(60,310,860,54);road(468,115,56,585);road(92,620,820,48);road(390,98,52,560);ctx.fillStyle='#d7d4b8';ctx.beginPath();ctx.arc(496,338,73,0,7);ctx.fill();ctx.fillStyle='#607171';ctx.beginPath();ctx.arc(496,338,54,0,7);ctx.fill();ctx.fillStyle='#89b477';ctx.beginPath();ctx.arc(496,338,42,0,7);ctx.fill();sites.forEach(building);ctx.fillStyle='#3c4748';ctx.fillRect(runway.x,runway.y,runway.w,runway.h);ctx.fillStyle='#f3eac3';ctx.setLineDash([26,16]);ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(runway.x+30,runway.y+runway.h/2);ctx.lineTo(runway.x+runway.w-30,runway.y+runway.h/2);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#d9e5d1';ctx.font='700 12px Noto Sans SC';ctx.textAlign='left';ctx.fillText('校园飞行跑道',runway.x+8,runway.y-8);for(let i=70;i<950;i+=35){tree(i,115+(i%3)*12);tree(i,800-(i%4)*10)}for(let i=150;i<880;i+=45){tree(i,410+(i%4)*16)}pedestrians.forEach(pedestrian);ctx.fillStyle='#2f7966';ctx.font='900 21px Noto Sans SC';ctx.textAlign='center';ctx.fillText('南开大学 · 津南校区',500,102);drawVehicle();ctx.restore();requestAnimationFrame(frame)}
function frame(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;update(dt);draw()}requestAnimationFrame(frame);
